/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/uiDemo/page/OpenMainScene.ls
 */
export class OpenMainSceneBase extends Laya.Scene {
    public closeBtn: Laya.Button;
}

