/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/page/Win.lh
 */
export class OpenSceneBase extends Laya.Box {
    public window: Laya.Image;
    public closeBtn: Laya.Button;
}

