/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/page/UsePanel.lh
 */
export class UsePanelRTBase extends Laya.Box {
    public panel!: Laya.Panel;
    public topLab!: Laya.Label;
}

