/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/interactive/ShapeDetection.lh
 */
export class ShapeDetectionRTBase extends Laya.View {
    public c1: Laya.Sprite;
    public c11: Laya.Sprite;
    public p1: Laya.Sprite;
    public p11: Laya.Sprite;
    public p2: Laya.Sprite;
    public p22: Laya.Sprite;
    public detectionType: Laya.RadioGroup;
}

