/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/page/Dialog.lh
 */
export class DialogRTBase extends Laya.Dialog {
    public dialogTitle: Laya.Label;
    public closeBtn: Laya.Button;
    public dialogText: Laya.TextArea;
}

