/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes&#x2F;uiDemo&#x2F;Msg.ls
 */
export class MsgRTBase extends Laya.Scene {
    public msgLab: Laya.Label;
}

