/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/UiMain.ls
 */
export class UiMainRTBase extends Laya.Scene {
    public topTab: Laya.Tab;
    public tabPage: Laya.ViewStack;
    public item0Tab: Laya.Tab;
    public item0Page: Laya.ViewStack;
    public item1Tab: Laya.Tab;
    public item1Page: Laya.ViewStack;
    public item2Tab: Laya.Tab;
    public item2Page: Laya.ViewStack;
    public item3Tab: Laya.Tab;
    public item3Page: Laya.ViewStack;
    public item4Tab: Laya.Tab;
    public item4Page: Laya.ViewStack;
}

