{
  "_$ver": 1,
  "_$id": "opoqgm9i",
  "_$runtime": "res://81b00a18-b16d-4395-8beb-e36956870010",
  "_$type": "Scene",
  "left": 0,
  "right": 0,
  "top": 0,
  "bottom": 0,
  "name": "Scene2D",
  "mouseThrough": true,
  "_$child": [
    {
      "_$id": "ykmtcgei",
      "_$type": "Label",
      "name": "Label",
      "width": 1334,
      "height": 52,
      "left": 0,
      "right": 0,
      "text": "UI Demo",
      "font": "SimHei",
      "fontSize": 38,
      "color": "#FFFFFF",
      "align": "center",
      "valign": "middle",
      "bgColor": "#5a7482",
      "leading": 0,
      "padding": "0,0,0,0"
    },
    {
      "_$id": "dijjo5qs",
      "_$prefab": "4b93552f-acf6-423c-8eb0-ec3267f873ba",
      "name": "closeBtn",
      "active": true,
      "x": 1302,
      "y": 0,
      "visible": true,
      "right": 0,
      "top": 0,
      "width": 32,
      "height": 32,
      "scaleX": 1,
      "scaleY": 1,
      "skewX": 0,
      "skewY": 0,
      "rotation": 0,
      "alpha": 1,
      "zOrder": 0,
      "blendMode": null,
      "mouseEnabled": true,
      "mouseThrough": false,
      "hitTestPrior": false,
      "drawCallOptimize": false,
      "cacheAs": "none",
      "anchorX": null,
      "anchorY": null,
      "disabled": null,
      "gray": null,
      "mask": null,
      "hitArea": null,
      "_filters": null,
      "_$child": [
        {
          "_$override": "jd6ni6ak",
          "skin": "res://310f8fa1-165e-45f6-ad06-ffebf0732f5e"
        }
      ]
    },
    {
      "_$id": "5wa5aoga",
      "_$type": "Image",
      "name": "Image",
      "y": 113,
      "width": 1334,
      "height": 637,
      "left": 0,
      "right": 0,
      "top": 113,
      "bottom": 0,
      "skin": "res://5988b77a-e4f1-4eb4-8571-32fbab23fab0",
      "sizeGrid": "7,14,10,13,0",
      "color": "#ffffff"
    },
    {
      "_$id": "gx83srlo",
      "_$type": "Panel",
      "name": "Panel",
      "x": 4.999999999999947,
      "y": 64.00000000000003,
      "width": 1333,
      "height": 49,
      "mouseEnabled": true,
      "_$child": [
        {
          "_$id": "t089ehw0",
          "_$var": true,
          "_$type": "Tab",
          "name": "topTab",
          "y": -1,
          "width": 1330,
          "height": 50,
          "mouseEnabled": true,
          "skin": "res://ef611a32-07e9-4411-882b-9bad38a237e6",
          "stateNum": null,
          "labels": "列表,UI基础使用,页面,2D 动画,进阶使用",
          "space": 10,
          "labelFont": null,
          "labelSize": 35,
          "labelColors": "#000000,#000000,#000000,#c0c0c0",
          "labelStroke": null,
          "labelStrokeColor": null,
          "labelAlign": null,
          "strokeColors": null
        }
      ]
    },
    {
      "_$id": "q4w4tglb",
      "_$var": true,
      "_$type": "ViewStack",
      "name": "tabPage",
      "y": 113,
      "width": 1334,
      "height": 617,
      "mouseEnabled": true,
      "top": 113,
      "bottom": 20,
      "selectedIndex": 0,
      "_$child": [
        {
          "_$id": "uipg6np1",
          "_$type": "Box",
          "name": "item0",
          "width": 1334,
          "height": 617,
          "mouseEnabled": true,
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "_$child": [
            {
              "_$id": "4wok6me2",
              "_$var": true,
              "_$type": "Tab",
              "name": "item0Tab",
              "x": 41.000000000000036,
              "y": 16.99999999999997,
              "width": 221,
              "height": 388,
              "mouseEnabled": true,
              "stateNum": null,
              "space": 25,
              "direction": "vertical",
              "labelFont": null,
              "labelSize": 30,
              "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0",
              "labelStroke": null,
              "labelStrokeColor": null,
              "labelAlign": null,
              "strokeColors": null,
              "_$child": [
                {
                  "_$id": "58wd2cvw",
                  "_$type": "Button",
                  "name": "item0",
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "背包列表",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "g6r1rjm9",
                  "_$type": "Button",
                  "name": "item1",
                  "y": 75,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "邮件列表",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "rr9z5k7c",
                  "_$type": "Button",
                  "name": "item2",
                  "y": 150,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "列表刷新",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "zyxg4e26",
                  "_$type": "Button",
                  "name": "item3",
                  "y": 225,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "循环列表",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "tfw7792c",
                  "_$type": "Button",
                  "name": "item4",
                  "y": 300,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "下拉框列表",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "fnln9cez",
                  "_$type": "Button",
                  "name": "item5",
                  "y": 375,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "树状列表",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                }
              ]
            },
            {
              "_$id": "qpdov7xn",
              "_$var": true,
              "_$type": "ViewStack",
              "name": "item0Page",
              "x": 304,
              "y": 10,
              "width": 1000,
              "height": 600,
              "mouseEnabled": true,
              "right": 30,
              "top": 10,
              "bottom": 7,
              "selectedIndex": 0,
              "_$child": [
                {
                  "_$id": "svnvkjtx",
                  "_$prefab": "9098b8d6-5a82-42e7-938b-7238e65e8ea1",
                  "name": "item0",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 600,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "jm7a363c",
                  "_$prefab": "ca2a578f-262d-45d0-a325-a4ee2d8c1fcc",
                  "name": "item1",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 600,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "br4g3k3z",
                  "_$prefab": "19d6f3dd-28ae-46f1-aaf9-1bd9af2f23a7",
                  "name": "item2",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0
                },
                {
                  "_$id": "cyg8p58j",
                  "_$prefab": "1eb52611-44e2-4f50-b621-c6b550843def",
                  "name": "item3",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 600,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "uqfivc6z",
                  "_$prefab": "e0fa1109-cba9-4622-8582-b6798f676276",
                  "name": "item4",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 600,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "fqktf4dr",
                  "_$prefab": "edeeb8a0-1892-43c4-8596-3f5b03353928",
                  "name": "item5",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0
                }
              ]
            }
          ]
        },
        {
          "_$id": "g57sscpn",
          "_$type": "Box",
          "name": "item1",
          "width": 1334,
          "height": 617,
          "visible": false,
          "mouseEnabled": true,
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "_$child": [
            {
              "_$id": "wzqkppmw",
              "_$var": true,
              "_$type": "Tab",
              "name": "item1Tab",
              "x": 41.000000000000036,
              "y": 16.99999999999997,
              "width": 221,
              "height": 388,
              "mouseEnabled": true,
              "stateNum": null,
              "space": 25,
              "direction": "vertical",
              "labelFont": null,
              "labelSize": 30,
              "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0",
              "labelStroke": null,
              "labelStrokeColor": null,
              "labelAlign": null,
              "strokeColors": null,
              "_$child": [
                {
                  "_$id": "bu4pgsq3",
                  "_$type": "Button",
                  "name": "item0",
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "进度相关",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "q9k0eaf4",
                  "_$type": "Button",
                  "name": "item1",
                  "y": 75,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "文本相关",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "d93olju2",
                  "_$type": "Button",
                  "name": "item2",
                  "y": 150,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "图片替换",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "nn0bbsoa",
                  "_$type": "Button",
                  "name": "item3",
                  "y": 225,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "事件穿透",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "jyd2oskx",
                  "_$type": "Button",
                  "name": "item4",
                  "y": 300,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "物理碰撞",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                },
                {
                  "_$id": "vawhvv90",
                  "_$type": "Button",
                  "name": "item5",
                  "y": 375,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "遮罩效果",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#faf8f8,#c0c0c0"
                }
              ]
            },
            {
              "_$id": "bpxitizd",
              "_$var": true,
              "_$type": "ViewStack",
              "name": "item1Page",
              "x": 304,
              "width": 1000,
              "height": 617,
              "mouseEnabled": true,
              "top": 0,
              "bottom": 0,
              "selectedIndex": 0,
              "_$child": [
                {
                  "_$id": "zg56xal9",
                  "_$prefab": "10a0686a-c4cb-4c87-ae67-17c3d1867a99",
                  "name": "item0",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": true,
                  "top": 10,
                  "bottom": 0,
                  "width": 1000,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": false,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "v1lsqoep",
                  "_$prefab": "8f239bb0-99be-40c4-9509-de6fd2fdf913",
                  "name": "item1",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": false,
                  "top": 10,
                  "bottom": 0,
                  "width": 1000,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null,
                  "disabled": null,
                  "gray": null,
                  "bgColor": null
                },
                {
                  "_$id": "tdjvsoam",
                  "_$prefab": "92b7ea1e-5903-492c-9a70-df8d2e899995",
                  "name": "item2",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": false,
                  "top": 10,
                  "bottom": 0,
                  "width": 1000,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": false,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "ad5vgiyc",
                  "_$prefab": "02149f27-0640-4076-a740-0147ada92f31",
                  "name": "item3",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": false,
                  "top": 10,
                  "bottom": 0,
                  "width": 1000,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "ypdrdaca",
                  "_$prefab": "57389d5c-adce-41e3-bd48-b9e7a69f1953",
                  "name": "item4",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": false,
                  "left": 0,
                  "right": 334,
                  "top": 10,
                  "bottom": 0,
                  "width": 666,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": false,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "y4et1pyz",
                  "_$prefab": "7e75a299-ac6b-4f6b-8109-4ee85a96d116",
                  "name": "item5",
                  "active": true,
                  "x": 0,
                  "y": 10,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 10,
                  "bottom": 0,
                  "width": 1000,
                  "height": 607,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                }
              ]
            }
          ]
        },
        {
          "_$id": "a5aiaxfe",
          "_$type": "Box",
          "name": "item2",
          "width": 1334,
          "height": 617,
          "visible": false,
          "mouseEnabled": true,
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "_$child": [
            {
              "_$id": "r0uonv2b",
              "_$var": true,
              "_$type": "Tab",
              "name": "item2Tab",
              "x": 41.000000000000036,
              "y": 16.99999999999997,
              "width": 221,
              "height": 388,
              "mouseEnabled": true,
              "stateNum": null,
              "space": 25,
              "direction": "vertical",
              "labelFont": null,
              "labelSize": 30,
              "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0",
              "labelStroke": null,
              "labelStrokeColor": null,
              "labelAlign": null,
              "strokeColors": null,
              "_$child": [
                {
                  "_$id": "azmi33up",
                  "_$type": "Button",
                  "name": "item0",
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "Panel窗口",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "njkxl1o0",
                  "_$type": "Button",
                  "name": "item1",
                  "y": 75,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "嵌套网页",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "0wmkyvfa",
                  "_$type": "Button",
                  "name": "item2",
                  "y": 150,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "打开主场景",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "r2kt2vhk",
                  "_$type": "Button",
                  "name": "item3",
                  "y": 225,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "打开小窗口",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "eao52krj",
                  "_$type": "Button",
                  "name": "item4",
                  "y": 300,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "打开弹窗",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                }
              ]
            },
            {
              "_$id": "ntnlekfs",
              "_$var": true,
              "_$type": "ViewStack",
              "name": "item2Page",
              "x": 304,
              "width": 1000,
              "height": 617,
              "mouseEnabled": true,
              "top": 0,
              "bottom": 0,
              "selectedIndex": 0,
              "_$child": [
                {
                  "_$id": "89kztrgr",
                  "_$prefab": "df942f45-c1cd-41dc-9f73-af30553689b9",
                  "name": "item0",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "left": 0,
                  "right": 0,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "g52vvia8",
                  "_$prefab": "cc465df6-7e24-4a46-809f-d8a2971461c4",
                  "name": "item1",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                }
              ]
            }
          ]
        },
        {
          "_$id": "ijup2ow4",
          "_$type": "Box",
          "name": "item3",
          "width": 1334,
          "height": 617,
          "visible": false,
          "mouseEnabled": true,
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "_$child": [
            {
              "_$id": "m3vncdsu",
              "_$var": true,
              "_$type": "Tab",
              "name": "item3Tab",
              "x": 41.000000000000036,
              "y": 16.99999999999997,
              "width": 221,
              "height": 388,
              "mouseEnabled": true,
              "stateNum": null,
              "space": 25,
              "direction": "vertical",
              "labelFont": null,
              "labelSize": 30,
              "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0",
              "labelStroke": null,
              "labelStrokeColor": null,
              "labelAlign": null,
              "strokeColors": null,
              "_$child": [
                {
                  "_$id": "c274mfvw",
                  "_$type": "Button",
                  "name": "item0",
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "图集动画",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "sqonccmy",
                  "_$type": "Button",
                  "name": "item1",
                  "y": 75,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "逐帧动画",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "s9ea4lme",
                  "_$type": "Button",
                  "name": "item2",
                  "y": 150,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "时间轴动画",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "ud4m6kka",
                  "_$type": "Button",
                  "name": "item3",
                  "y": 225,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "骨骼动画",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "odutvbot",
                  "_$type": "Button",
                  "name": "item4",
                  "y": 300,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "res://0d62d481-2dce-46ee-9e7c-15d5cdd14c8d",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "缓动动画",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                }
              ]
            },
            {
              "_$id": "rk0pf8y1",
              "_$var": true,
              "_$type": "ViewStack",
              "name": "item3Page",
              "x": 304,
              "width": 1000,
              "height": 617,
              "mouseEnabled": true,
              "top": 0,
              "bottom": 0,
              "selectedIndex": 0,
              "_$child": [
                {
                  "_$id": "8ng2gzmk",
                  "_$prefab": "44f6030f-750d-4942-92f9-2010100b774a",
                  "name": "item0",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null,
                  "_$child": [
                    {
                      "_$override": "k0ftacui",
                      "skin": "resources/UI/images/bg/bg01.png"
                    }
                  ]
                },
                {
                  "_$id": "fdrrkpgk",
                  "_$prefab": "490589fe-001c-40b6-b03a-baa5c279a1c5",
                  "name": "item1",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "eda68bqe",
                  "_$prefab": "149bbad9-e30f-4e49-8bd0-5c9787c9eb5d",
                  "name": "item2",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "9ycliad9",
                  "_$prefab": "204e7719-2f9f-4007-b69a-c70bc57a1603",
                  "name": "item3",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "ng28ecii",
                  "_$prefab": "263a2f59-9b8f-4438-8268-8a6e03b8ead9",
                  "name": "item4",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 617,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                }
              ]
            }
          ]
        },
        {
          "_$id": "qdgw5kuj",
          "_$type": "Box",
          "name": "item4",
          "width": 1334,
          "height": 617,
          "visible": false,
          "mouseEnabled": true,
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "_$child": [
            {
              "_$id": "lsvuj3ay",
              "_$var": true,
              "_$type": "Tab",
              "name": "item4Tab",
              "x": 41.000000000000036,
              "y": 16.99999999999997,
              "width": 221,
              "height": 388,
              "mouseEnabled": true,
              "skin": "resources/UI/images/comp/button.png",
              "stateNum": null,
              "space": 25,
              "direction": "vertical",
              "labelFont": null,
              "labelSize": 30,
              "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0",
              "labelStroke": null,
              "labelStrokeColor": null,
              "labelAlign": null,
              "strokeColors": null,
              "_$child": [
                {
                  "_$id": "l1ghbw0u",
                  "_$type": "Button",
                  "name": "item0",
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "resources/UI/images/comp/button.png",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "手势摇杆",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "690fd798",
                  "_$type": "Button",
                  "name": "item1",
                  "y": 75,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "resources/UI/images/comp/button.png",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "图形碰撞",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "znkexx3o",
                  "_$type": "Button",
                  "name": "item2",
                  "y": 150,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "resources/UI/images/comp/button.png",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "TiledMap",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                },
                {
                  "_$id": "006vrx1m",
                  "_$type": "Button",
                  "name": "item3",
                  "y": 225,
                  "width": 180,
                  "height": 50,
                  "mouseEnabled": true,
                  "skin": "resources/UI/images/comp/button.png",
                  "sizeGrid": "12,12,12,12,0",
                  "label": "A*寻路",
                  "labelFont": "SimHei",
                  "labelSize": 30,
                  "labelColors": "#000000,#ffffff,#ffffff,#c0c0c0"
                }
              ]
            },
            {
              "_$id": "hl47fj58",
              "_$var": true,
              "_$type": "ViewStack",
              "name": "item4Page",
              "x": 304,
              "y": 20,
              "width": 1000,
              "height": 597,
              "mouseEnabled": true,
              "top": 20,
              "bottom": 0,
              "selectedIndex": 0,
              "_$child": [
                {
                  "_$id": "lzs3zpsl",
                  "_$prefab": "48159037-ef12-48d0-85cd-2152fcd5725e",
                  "name": "item0",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 597,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "5x8ejsop",
                  "_$prefab": "4203a717-afdb-43d6-a3a7-3edcec43bfe4",
                  "name": "item1",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 597,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null
                },
                {
                  "_$id": "zb0g8dnl",
                  "_$prefab": "dd073997-c2c7-4ba9-a9a3-7be5fad0b690",
                  "name": "item2",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 597,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null,
                  "disabled": null,
                  "gray": null,
                  "mask": null,
                  "hitArea": null,
                  "_filters": null
                },
                {
                  "_$id": "vo8q7dun",
                  "_$prefab": "7ddfd55a-13f0-403d-af20-59addbffb4b8",
                  "name": "item3",
                  "active": true,
                  "x": 0,
                  "y": 0,
                  "visible": false,
                  "top": 0,
                  "bottom": 0,
                  "width": 1000,
                  "height": 597,
                  "scaleX": 1,
                  "scaleY": 1,
                  "skewX": 0,
                  "skewY": 0,
                  "rotation": 0,
                  "alpha": 1,
                  "zOrder": 0,
                  "blendMode": null,
                  "mouseEnabled": true,
                  "mouseThrough": false,
                  "hitTestPrior": false,
                  "drawCallOptimize": false,
                  "cacheAs": "none",
                  "anchorX": null,
                  "anchorY": null,
                  "disabled": false,
                  "gray": false,
                  "mask": null,
                  "hitArea": null,
                  "_filters": null
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}