/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/list/LoopList.lh
 */
export class LoopListRTBase extends Laya.View {
    public hList: Laya.List;
}

