/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab&#x2F;uiDemo&#x2F;useUI&#x2F;Mask.lh
 */
export class MaskRTBase extends Laya.View {
    public bg2: Laya.Image;
    public _mask: Laya.Sprite;
    public bg3Mask: Laya.Sprite;
    public _hitArea: Laya.Sprite;
}

