/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab&#x2F;uiDemo&#x2F;useUI&#x2F;Progress.lh
 */
export class ProgressRTBase extends Laya.View {
    public loading2: Laya.ProgressBar;
    public loadText: Laya.Text;
}

